### ISSUE TITLE
improve config and priority accent

### ISSUE THREAD

**Issue by vczEz** [artyompetrov/AutoDefine_oxfordlearnersdictionaries#11]
if addon doesn´t find audio in british accent, set american audio.
can you change the config of the addon? for example:

"1. word": {
          " 1. SOURCE_FIELD": 0,
          " 2. CLEAN_HTML_IN_SOURCE_FIELD": false,
         
      },
  "2. definition": {
	  " 1. DEFINITION":  true,
          " 2. DEFINITION_FIELD": 1,
	  " 3. REPLACE_BY": "____",
	  " 4. MAX_EXAMPLES_COUNT_PER_DEFINITION": 3,
          " 5. MAX_DEFINITIONS_COUNT_PER_PART_OF_SPEECH": 3
      },
  "3. audio": {
          
          " 1. AUDIO": false,
          " 2. AUDIO_FIELD": 2,
	  " 3. CORPUS": "American",
      },
  "4. image": {
          
	  " 1. OPEN_IMAGES_IN_BROWSER": false,
          " 2. SEARCH_APPEND": "",
	  " 3. OPEN_IMAGES_IN_BROWSER_LINK": "https://www.google.com/search?q=$&tbm=isch&safe=off&tbs&hl=en&sa=X",
          " 4. or use this link instead": "https://www.istockphoto.com/search/2/image?phrase=$",
      },
  "5. ipa": {
          
         " 1. PHONETICS": false,
         " 2. PHONETICS_FIELD": 3,
      },
  "6. shortcuts": {
          "1. PRIMARY_SHORTCUT": "ctrl+alt+e"
      }

**Comment by artyompetrov** [comment]
>>if addon doesn´t find audio in british accent, set american audio.
Can you give an example of such word so I could test new algorithm?

**Comment by artyompetrov** [comment]
Done!
