### ISSUE TITLE
Is that possible to insert mp3 audio?

### ISSUE THREAD

**Issue by shenweiyang** [artyompetrov/AutoDefine_oxfordlearnersdictionaries#12]
Dear Artyompetrov,

I am using this addon to learn English now, and a big fan of your addon!
I am using it on windows now, but I also want to use it on my iPhone. 
Unfortunately, anki iOS version does not support .ogg audio file.
Is that possible to insert mp3 audio into the cards?

**Comment by tvhong** [comment]
I also faced this issue recently.

So, I've created a pull request to add an "AUDIO_FORMAT" config. If this gets merged, we'll have the ability to download mp3 files.

**Comment by artyompetrov** [comment]
I merged @tvhong pull request! Thank you!
