### ISSUE TITLE
Is that possible to change the font size?

### ISSUE THREAD

**Issue by shenweiyang** [artyompetrov/AutoDefine_oxfordlearnersdictionaries#13]
Dear Artyompetrov,

One more question, is that possible to change the font size or distance between lines? 
It would be great if we could create a card with a compact layout suitable for mobile devices.
This add-on is fantastic and I'm using it everyday, best if more suitable for smartphones.

**Comment by artyompetrov** [comment]
Hello! You can do so by editing card template:

![image](https://user-images.githubusercontent.com/31510247/226183375-6ab38ce8-f46e-4da6-ad04-1b3a2ea06ce2.png)

Code to copy:
```
<style>
div
{
  font-size: 200%;
}
</style>
```
