### ISSUE TITLE
Anki Processing

### ISSUE THREAD

**Issue by Geniusssmit** [artyompetrov/AutoDefine_oxfordlearnersdictionaries#14]
**Describe the bug**
after making defs for 2-3 words this appears and I can't use anki at all until I kill it.
![image](https://user-images.githubusercontent.com/24941285/215351575-d96520f9-7f32-43bd-999e-9bffe525fb76.png)

**To Reproduce**
use the addon in anki browser 2-3 times

**Expected behavior**
should work

**Debug info:**
 - Anki Version 2.1.54
 - OS: Windows 10

**Additional context (e.g., exception)**

**Comment by artyompetrov** [comment]
Hello! Unfortunately, I can not reproduce this problem on anki ⁨2.1.54 and Windows 10.
Can you create a video illustration of the problem. Maybe you have noticed that the problem appears only on specific words?
Also there can be a conflict with another add-on. Do you use another addons?

**Comment by artyompetrov** [comment]
@Geniusssmit you don't answer, so will repeat the message in case you missed that:

Hello! Unfortunately, I can not reproduce this problem on anki ⁨2.1.54 and Windows 10.
Can you create a video illustration of the problem. Maybe you have noticed that the problem appears only on specific words?
Also there can be a conflict with another add-on. Do you use another addons?

**Comment by Geniusssmit** [comment]
Sorry I didn't answer. I've reinstalled anki and the addon, now it works as expected. Thank you for the addon.
