### ISSUE TITLE
Verb Forms

### ISSUE THREAD

**Issue by Kruglianin** [artyompetrov/AutoDefine_oxfordlearnersdictionaries#15]
Hi Artem.
Is it possible to get also all forms of the verb on the word page?
![image](https://user-images.githubusercontent.com/55271215/223978098-a8fddbbc-f3f9-4d60-b7a3-50dfd7e40875.png)

PS. Продублирую и разверну подробно на русском. (я носитель)
Привет, Артём.
Полагаю затея неподъёмная, но пожалуй напишу.
Если ли возможность (особенно касается глаголов) вытащить все представленные на странице глагольные формы с IPA и озвучкой?
Например есть глагол "become".
Аддон (впрочем и API) вернёт его форму в инфинитиве.
Было бы здорово зацепить все его формы, а именно помимо present simple достать ещё форму для he / she / it + past simple + past participle + -ing form. (как на фото выше)
Если достать это с IPA и аудио это вообще было бы круто.
Мне кажется парсером немного легче к этому достучатся, но я вот совсем ни разу не программист, поэтому и рыдаю тут.
Спасибо Тебе заранее.
Аддон очень крутой!

**Comment by Kruglianin** [comment]
Спасибо за возможность!
Сколько не пробовал готовые колоды, конкретно в моём случае усваивается инфа по карточкам только собственного производства. Как говорится «Без труда не выловишь и рыбку из пруда».
Я фанат Оксфордского словаря и отметил что Твой аддон отлично с ним взаимодействует как в авто так и в полуавтоматическом режиме.
Супер мечта это вообще иметь возможность при нажатии видеть и выбирать  какую часть речи хочешь получить для карточки, когда искомое слово полифункциональное и может быть разной частью речи (типа глагол и существительное и т.д), но это уже полагаю другой объём работы,-совсем другой.
Спасибо Тебе ещё раз!

**Comment by artyompetrov** [comment]
Супер мечта это вообще иметь возможность при нажатии видеть и выбирать какую часть речи хочешь получить для карточки, когда искомое слово полифункциональное и может быть разной частью речи (типа глагол и существительное и т.д) - если так сделать, то в колоде появятся дубликаты.

**Comment by artyompetrov** [comment]
В ветке https://github.com/artyompetrov/AutoDefine_oxfordlearnersdictionaries/tree/add-bulk-and-default-template 
опубликовал новую версию, она умеет:
Извлекать глагольные формы (пока без транскрипций и произношения)
Поддерживает пакетные операци - например можно пакетно перегнать старые карточки через add-on
Содержит проработанный темплейт карточки 
выглядит вот так:

![image](https://github.com/artyompetrov/AutoDefine_oxfordlearnersdictionaries/assets/31510247/7c809759-22f1-4da5-9d63-1d1580bad173)
![image](https://github.com/artyompetrov/AutoDefine_oxfordlearnersdictionaries/assets/31510247/f1314362-4f5d-4b1f-b04f-bf57b84026ea)
![image](https://github.com/artyompetrov/AutoDefine_oxfordlearnersdictionaries/assets/31510247/b0861974-784b-4ffc-a043-2ab1a708ec30)

Не знаю пока когда буду релизить, можно пока потестировать версию из гита, если есть желание.

**Comment by artyompetrov** [comment]
глагольные формы:
![image](https://github.com/artyompetrov/AutoDefine_oxfordlearnersdictionaries/assets/31510247/bfacd809-c267-4400-892b-0dc55c6c3f39)

**Comment by artyompetrov** [comment]
added verb forms support
