### ISSUE TITLE
Auto insertion mode: append or write?

### ISSUE THREAD

**Issue by valuex** [artyompetrov/AutoDefine_oxfordlearnersdictionaries#18]
Right now `AutoDefine_oxfordlearnersdictionaries` is working in `WRITE` mode, that is, to remove the contents existed in the `back` field.
How about add one feature to check whether there is any existed content? If existed, append the seached content in the `back` field.
My idea:
``` python
if content exsited in the back field:
     if searched content in the back field:
           yes, clicked more than once, no need for updating
append
```

**Comment by artyompetrov** [comment]
Anki allows to create card templates (it is called card types), you can use multiple fields on one side of the card. There is no need to use append.

Also I am preparing an update with such a template built imbedded into the add-on. It will be ready soon.
