### ISSUE TITLE
"The software is hanging and cannot be closed."

### ISSUE THREAD

**Issue by namequan** [artyompetrov/AutoDefine_oxfordlearnersdictionaries#20]
**Describe the bug**
"The software is hanging and cannot be closed."

**To Reproduce**
You can watch video

https://github.com/artyompetrov/AutoDefine_oxfordlearnersdictionaries/assets/138419306/3e738b81-bb58-4e4a-9ce4-c509ddd8a53e

**Expected behavior**
"The [Processing] popup does not appear and the software is not hung."

**Debug info:**
 - Anki Version [2.1.49 (dc80804a)⁩]
 - OS: [Windows 7]

**Additional context (e.g., exception)**

**Comment by artyompetrov** [comment]
please provide screenshot of your add-ons installed. It seems like there is a conflict.

**Comment by artyompetrov** [comment]
Closing because no additional info was provided
