### ISSUE TITLE
not pulling audio any more 

### ISSUE THREAD

**Issue by Aurva** [artyompetrov/AutoDefine_oxfordlearnersdictionaries#22]
**Describe the bug**
Audio pronunciation is not working 
![image](https://github.com/artyompetrov/AutoDefine_oxfordlearnersdictionaries/assets/148464938/ecf11e22-d25a-4215-838a-2a418dd527db)

**Comment by artyompetrov** [comment]
I changed the add-on a little. Please update and confirm that it is working again.

**Comment by Aurva** [comment]
It's functioning well. Thank you very much for addressing this issue.
![image](https://github.com/artyompetrov/AutoDefine_oxfordlearnersdictionaries/assets/148464938/542edbc0-b392-497d-a655-3438c87731a0)
