### ISSUE TITLE
word calf produces weird definition

### ISSUE THREAD

**Issue by Geniusssmit** [artyompetrov/AutoDefine_oxfordlearnersdictionaries#26]
calf
![image](https://github.com/artyompetrov/AutoDefine_oxfordlearnersdictionaries/assets/24941285/d145ac8f-195c-4bab-b687-5442e0d76675)
Word_not_replaced

**Comment by artyompetrov** [comment]
This works as designed. Word calf has irregular plural form so that it cannot be replaced with underscores (at least with current word replacing algorithm). This red marks notify a user to replace the word occurances manually.
