### ISSUE TITLE
failed to load

### ISSUE THREAD

**Issue by catzoe1201** [artyompetrov/AutoDefine_oxfordlearnersdictionaries#5]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Debug info:**
 - Anki Version [e.g. 2.1.5]
 - OS: [Linux, Mac, Windows]
<img width="406" alt="截圖 2022-08-16 上午1 41 07" src="https://user-images.githubusercontent.com/105838563/184687135-5532454a-303b-4458-8732-f7c516a9c688.png">

**Additional context (e.g., exception)**

**Comment by artyompetrov** [comment]
@catzoe1201 hello! I released a new version, please check if the problem is gone.

**Comment by catzoe1201** [comment]
[image: 截圖 2022-08-16 下午1.06.41.png]

Zoe Chen ***@***.***> 於 2022年8月16日 週二 下午1:05寫道：

**Comment by phonzia** [comment]
![image](https://user-images.githubusercontent.com/3022520/184834239-c0046b82-449a-476d-9090-64fe9a63e07a.png)
failed to load in macbook pro 2021

**Comment by artyompetrov** [comment]
@catzoe1201 @phonzia I fixed it, please update

**Comment by catzoe1201** [comment]
thanks!


artyompetrov ***@***.***> 於 2022年8月16日 週二 晚上8:34寫道：

**Comment by catzoe1201** [comment]
Thank you!!
