### ISSUE TITLE
British accent

### ISSUE THREAD

**Issue by mofiree** [artyompetrov/AutoDefine_oxfordlearnersdictionaries#6]
Is it possible to use?

**Comment by artyompetrov** [comment]
Maybe later I will add British accent. Though it will be time costly. Pull request is appreciated.

**Comment by artyompetrov** [comment]
here is beautiful api for british version https://github.com/NearHuscarl/oxford-dictionary-api
may use it to implement british version support

**Comment by artyompetrov** [comment]
added British pronunciation
