### ISSUE TITLE
change where to search images

### ISSUE THREAD

**Issue by vczEz** [artyompetrov/AutoDefine_oxfordlearnersdictionaries#9]
Sometimes google is not good for this, Example:
![Screenshot_162](https://user-images.githubusercontent.com/78620977/192123939-78bc94b5-b9c2-4509-8ff5-581028e67cdc.png)

can you change this? 
example you can change this for istock or other page where people buy images etc. 

https://www.istockphoto.com/

![Screenshot_161](https://user-images.githubusercontent.com/78620977/192123926-7db438ec-420b-4b58-af24-a14cd5555276.png)

**Comment by artyompetrov** [comment]
Created 11. OPEN_IMAGES_IN_BROWSER_LINK param in config file, you can use any website that receives the searching word through url get parameter.

**Comment by vczEz** [comment]
Thanks!!!!
![Screenshot_164](https://user-images.githubusercontent.com/78620977/193477736-1f90a5f3-1605-4896-a443-f6b90c27bd40.png)
